### ISSUE TITLE
Deploy fails with Python3.4.

### ISSUE THREAD

**Issue by btimby** [smartfile/django-session-jwt#2]
The tests pass under Python3.4 but deploy fails. This is not critical as any successful deploy fulfills requirements, but I would prefer to fix this.

**Comment by btimby** [comment]
The error is:

```
2020-05-17 16:52:39 URL:https://bootstrap.pypa.io/get-pip.py [1868059/1868059] -> "-" [1]
Traceback (most recent call last):
  File "<stdin>", line 23470, in <module>
  File "<stdin>", line 198, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/cli/main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/cli/autocompletion.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/cli/main_parser.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/cli/progress_bars.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/utils/logging.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_internal/utils/misc.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/tmp/tmpekynjhkr/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
RuntimeError: Python 3.5 or later is required
Couldn't install pip, setuptools, twine or wheel.
```

**Comment by btimby** [comment]
Fixed, I moved the deploy to a stage, it now only runs once after all test jobs complete.
